# Fichier docker-compose.yml pour le développement local de Learning Locker
version: '3.8'

services:
  # MongoDB pour stocker les traces xAPI
  mongodb:
    image: mongo:latest
    container_name: addlearn_mongodb
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=learninglocker
    ports:
      - "27017:27017"
    networks:
      - lrs_network

  # Redis pour le cache
  redis:
    image: redis:alpine
    container_name: addlearn_redis
    ports:
      - "6379:6379"
    networks:
      - lrs_network

  # UI de Learning Locker
  ui:
    image: learninglocker/learning-locker-ui:latest
    container_name: addlearn_ui
    environment:
      - MONGO_URL=mongodb://mongodb:27017/learninglocker
      - REDIS_URL=redis://redis:6379
      - APP_SECRET=${APP_SECRET}
      - UI_PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - lrs_network

  # API de Learning Locker
  api:
    image: learninglocker/learning-locker-api:latest
    container_name: addlearn_api
    environment:
      - MONGO_URL=mongodb://mongodb:27017/learninglocker
      - REDIS_URL=redis://redis:6379
      - APP_SECRET=${APP_SECRET}
      - API_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - lrs_network

  # Worker pour le traitement asynchrone
  worker:
    image: learninglocker/learning-locker-worker:latest
    container_name: addlearn_worker
    environment:
      - MONGO_URL=mongodb://mongodb:27017/learninglocker
      - REDIS_URL=redis://redis:6379
      - APP_SECRET=${APP_SECRET}
    depends_on:
      - mongodb
      - redis
    networks:
      - lrs_network

networks:
  lrs_network:
    driver: bridge

  # RStudio pour l'analyse avancée
  rstudio:
    image: rocker/rstudio:latest
    container_name: addlearn_rstudio
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD}
      - ROOT=TRUE
    ports:
      - "${RSTUDIO_PORT}:8787"
    volumes:
      - ./analytics/R:/home/rstudio/analytics
    networks:
      - lrs_network

volumes:
  mongo_data:
